# Generated by Django 6.0 on 2025-12-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='craeted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='postview',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
        ),
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='post.post'),
        ),
    ]
